### ISSUE TITLE
`npm install --build-from-source` fails

### ISSUE THREAD

**Issue by mmomtchev** [mmomtchev/pymport#11]
`npm install --build-from-source` fails because `node-addon-api` is a `devDependency`

```
Error: Cannot find module 'node-addon-api'
Require stack:
- /home/mmom/src/test/node_modules/pymport/[eval]
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at [eval]:1:1
    at Script.runInThisContext (vm.js:134:12)
    at Object.runInThisContext (vm.js:310:38)
    at internal/process/execution.js:81:19
    at [eval]-wrapper:6:22
    at evalScript (internal/process/execution.js:80:60) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/mmom/src/test/node_modules/pymport/[eval]' ]
```

Workaround is to manually install `node-addon-api` 
```
npm install node-addon-api
```

**Comment by mmomtchev** [comment]
Fixed by https://github.com/mmomtchev/pymport/commit/32cf93dde7050699347f144375aa0409d5fed183
